// =================================================================================
// 1. 전역 변수 및 초기 데이터 (Global Variables & Initial Data)
// =================================================================================

let grossSalaryInput, salaryFrequencySelect, netIncomeInput, modeToggleCheckbox;
let taxFrequencySelect, preTaxFrequencySelect, postTaxFrequencySelect, expenseFrequencySelect;
let summaryFrequencySelect;
let annualSalarySummaryDisplay, summaryGrossSalary, summaryTotalTaxes, summaryTotalPreTax, summaryTotalPostTax, summaryNetSalary, summaryTotalExpenses, summaryRemainingBudget, summaryAdvancedView;
const taxInputs = {}, preTaxDeductInputs = {}, postTaxDeductInputs = {}, expenseInputs = {};
let customIncomeList, customTaxList, customPreTaxDeductList, customPostTaxDeductList;
let languageToggleBtn, darkmodeToggleBtn, currencyToggleBtn;
let exportJsonBtn, importJsonBtn, importJsonInput, clearAllDataBtn, printBtn, emailBtn, shareBtn;
let aiReportBtn, aiReportBox, apiKeyInput;
let budgetRuleSelect, budgetRuleBreakdown;
let taxChartInstance, preTaxDeductChartInstance, postTaxDeductChartInstance, expensesChartInstance, budgetDistributionChartInstance, historyChartInstance;
let modalContainer, modalTitle, modalList, modalCloseBtn;
let advancedModeContainer, simpleModeContainer;
let goalNameInput, goalTargetInput, addGoalBtn, goalListContainer;
let debtNameInput, debtBalanceInput, debtRateInput, debtPaymentInput, addDebtBtn, debtListContainer, debtExtraPaymentInput, debtResultContainer;
let recordHistoryBtn;
let categoryNameInput, categoryTypeSelect, addCategoryBtn, categoryListContainer;
let expenseNameInput, expenseAmountInput, expenseCategorySelect, addExpenseBtn, expenseListContainer;
let dashboardNetIncome, dashboardTotalExpenses, dashboardRemaining, dashboardSavingsRate;
let scenarioIncomeChangeInput, scenarioExpenseChangeInput, runScenarioBtn, scenarioResultsContainer;

const data = {
    calculationMode: 'simple',
    netIncome: 0,
    grossSalary: 0,
    salaryFrequency: 'monthly',
    customIncomes: [],
    summaryFrequency: 'monthly',
    currency: 'USD',
    frequencies: { tax: 'monthly', preTax: 'monthly', postTax: 'monthly', expense: 'monthly' },
    taxes: { federal: 0, state: 0, oasdi: 0, medicare: 0, casdi: 0, custom: [] },
    preTaxDeductions: { medical: 0, dental: 0, vision: 0, '401k-trad': 0, custom: [] },
    postTaxDeductions: { spp: 0, adnd: 0, '401k-roth': 0, ltd: 0, 'critical-illness': 0, 'accident-insurance': 0, 'legal-services': 0, custom: [] },
    expenses: {
        rent: 0, utilities: 0, internet: 0, phone: 0, groceries: 0, dining: 0, transport: 0, shopping: 0, health: 0,
        entertainment: 0, insurance: 0, donation: 0, travel: 0, pets: 0, children: 0,
        custom: []
    },
    categories: [
        { id: 1, name: 'Rent/Mortgage', type: 'needs' }, { id: 2, name: 'Utilities', type: 'needs' }, { id: 3, name: 'Groceries', type: 'needs' },
        { id: 4, name: 'Transportation', type: 'needs' }, { id: 5, name: 'Health/Wellness', type: 'needs' }, { id: 6, name: 'Insurance', type: 'needs' },
        { id: 7, name: 'Phone Bill', type: 'needs' }, { id: 8, name: 'Internet', type: 'needs' }, { id: 9, name: 'Children', type: 'needs' },
        { id: 10, name: 'Dining Out', type: 'wants' }, { id: 11, name: 'Shopping', type: 'wants' }, { id: 12, name: 'Entertainment', type: 'wants' },
        { id: 13, name: 'Travel', type: 'wants' }, { id: 14, name: 'Pets', type: 'wants' }, { id: 15, name: 'Donation', type: 'wants' }
    ],
    goals: [],
    debts: [],
    history: [],
    budgetRule: '50-30-20',
    currentLanguage: 'ko',
    isDarkMode: false
};

const ITEM_CATEGORIES = {
    'tax-federal-1': 'fixed', 'tax-state-1': 'fixed', 'tax-oasdi-1': 'fixed', 'tax-medicare-1': 'fixed', 'tax-casdi-1': 'fixed',
    'deduct-medical-1': 'needs', 'deduct-dental-1': 'needs', 'deduct-vision-1': 'needs', 'deduct-ltd-1': 'needs', 'deduct-adnd-1': 'needs',
    'deduct-critical-illness-1': 'needs', 'deduct-accident-insurance-1': 'needs', 'deduct-legal-services-1': 'wants',
    'deduct-401k-trad-1': 'savings', 'deduct-401k-roth-1': 'savings', 'deduct-spp-1': 'savings'
};

const translations = {
    en: {
        app_title: 'Budget Tool',
        section_calculation_mode_title: 'Calculation Mode',
        mode_simple: 'Simple',
        mode_advanced: 'Advanced',
        tooltip_calculation_mode: "Choose your calculation method. 'Simple Mode' uses your after-tax net income. 'Advanced Mode' allows for a detailed breakdown starting from your gross income and deductions.",
        section_net_income_title: 'Net Income',
        label_net_income: 'Monthly Net Income (After-Tax)',
        tooltip_net_income: "Enter the actual amount of money you receive in your bank account monthly, after all taxes and deductions.",
        section_salary_title: 'Gross Income',
        tooltip_salary: "Enter your total salary before any taxes or deductions are taken out. Use 'Add Custom Income' for irregular earnings.",
        label_base_salary: 'Base Salary',
        frequency_monthly: 'Monthly',
        frequency_annually: 'Annual',
        frequency_weekly: 'Weekly',
        frequency_bi_weekly: 'Bi-Weekly',
        btn_add_income: 'Add Custom Income',
        label_annual_salary: 'Annual Gross Income:',
        section_taxes_title: 'Taxes',
        tooltip_taxes: "Enter all tax amounts that are withheld from your paycheck.",
        label_frequency: 'Frequency',
        label_federal_withholding: 'Federal Withholding',
        label_state_tax: 'State Tax',
        label_oasdi: 'OASDI',
        label_medicare: 'Medicare',
        label_ca_sdi: 'CA SDI',
        btn_add_item: 'Add Custom Item',
        section_pre_tax_title: 'Pre-Tax Deductions',
        tooltip_pre_tax: "Items deducted from your gross income before taxes are calculated, such as 401(k) contributions or certain insurance premiums.",
        label_medical_premium: 'Medical Premium',
        label_dental_premium: 'Dental Premium',
        label_vision_premium: 'Vision Premium',
        label_401k_traditional: '401k Traditional',
        section_post_tax_title: 'Post-Tax Deductions',
        tooltip_post_tax: "Items deducted from your paycheck after taxes have been paid.",
        label_spp: 'SPP',
        label_adnd: 'AD&D',
        label_401k_roth: '401k Roth',
        label_ltd: 'LTD',
        label_critical_illness: 'Critical Illness',
        label_accident_insurance: 'Accident Insurance',
        label_legal_services: 'Legal Services',
        section_expenses_title: 'Expense Management',
        tooltip_expenses: "Enter all your regular expenses based on your Net Income.",
        label_rent_mortgage: 'Rent/Mortgage',
        label_utilities: 'Utilities',
        label_internet: 'Internet',
        label_phone: 'Phone Bill',
        label_groceries: 'Groceries',
        label_dining_out: 'Dining Out',
        label_transportation: 'Transportation',
        label_shopping: 'Shopping',
        label_health_wellness: 'Health/Wellness',
        label_entertainment: 'Entertainment',
        label_insurance: 'Insurance',
        label_donation: 'Donation',
        label_travel: 'Travel',
        label_pets: 'Pets',
        label_children: 'Children',
        section_summary_title: 'Budget Summary',
        tooltip_summary: "This is a complete overview of your finances based on your inputs.",
        label_summary_frequency: 'Summary Frequency',
        label_gross_salary: 'Gross Salary:',
        label_total_taxes: 'Total Taxes:',
        label_total_pre_tax: 'Total Pre-Tax Deductions:',
        label_total_post_tax: 'Total Post-Tax Deductions:',
        label_net_salary: 'Net Salary (Take-Home):',
        label_total_expenses: 'Total Expenses:',
        label_remaining_budget: 'Remaining Budget:',
        label_savings_rate: 'Savings Rate',
        section_budget_rule_title: 'Budget Rule Application',
        tooltip_budget_rule: "Select a popular budgeting rule to visually compare your spending against a target.",
        rule_50_30_20_title: '50/30/20 Rule (Needs/Wants/Savings)',
        rule_70_20_10_title: '70/20/10 Rule (Spending/Savings/Debt)',
        rule_80_20_title: '80/20 Rule (Spending/Savings)',
        section_ai_title: 'AI Expense Report',
        tooltip_ai_report: "Generates an analysis of your financial health based on the data you've entered and provides actionable advice.",
        ai_report_placeholder: 'Click "Generate AI Report" for insights.',
        section_data_title: 'Data Management',
        tooltip_data_management: "Save your current data to a file (Export) or load data from a previously saved file (Import).",
        btn_export: 'Export',
        btn_import: 'Import',
        btn_clear_all_data: 'Clear Data',
        btn_print: 'Print',
        btn_email: 'Email',
        btn_share: 'Share',
        custom_item_name: 'Item Name',
        custom_income_name: 'Income Name',
        custom_item_amount: 'Amount',
        custom_item_category: 'Category',
        remove: 'Remove',
        confirm_clear_data: 'Are you sure you want to clear all data?',
        confirm_import_data: 'This will overwrite existing data. Continue?',
        invalid_json: 'Invalid JSON file.',
        alert_data_loaded: "Data loaded successfully!",
        tag_needs: 'Needs',
        tag_wants: 'Wants',
        tag_savings: 'Savings',
        tag_debt: 'Debt',
        tag_fixed: 'Fixed',
        rule_category_needs: 'Needs',
        rule_category_wants: 'Wants',
        rule_category_savings: 'Savings',
        rule_category_savings_debt: 'Savings & Debt',
        rule_category_spending: 'Spending',
        rule_category_debt: 'Debt Repayment',
        rule_category_surplus: 'Surplus (Unallocated)',
        modal_title_needs: 'Needs Items',
        modal_title_wants: 'Wants Items',
        modal_title_savings: 'Savings Items',
        modal_title_savings_debt: 'Savings & Debt Items',
        modal_title_spending: 'Spending Items',
        modal_title_debt: 'Debt Items',
        report_local_generating: "Generating Local Analysis Report...",
        report_local_failed: "Failed to generate local report. Please check the data.",
        report_local_title: "Financial Health Analysis",
        report_local_summary_title: "1. Executive Summary",
        report_local_summary_text: "Based on a {summaryFreq} net income of {netIncome}, your savings rate is <strong>{savingsRate}%</strong>. You have a remaining surplus of <strong>{remaining}</strong>. Your spending habits show strengths in <strong>{strength}</strong>, with areas for improvement in <strong>{weakness}</strong>.",
        report_local_strength: "prudent savings",
        report_local_weakness: "high discretionary spending",
        report_local_no_weakness: "balanced management",
        report_local_recommendation_title: "2. Recommended Actions",
        report_local_tip_overspending: "Your spending on '{category}' ({amount}) exceeds the budget rule. Consider reducing this by about 10-15%.",
        report_local_tip_high_wants: "Your discretionary spending ('Wants') makes up {wantsPercentage}% of your income. Reviewing these items could significantly boost your savings.",
        report_local_tip_low_savings: "Your savings rate is {savingsRate}%. To achieve your financial goals faster, consider allocating any surplus or cutting back on non-essential spending to increase this rate.",
        report_local_tip_surplus: "You have a surplus of {remaining}! Allocating this to your savings or investments could generate an estimated {annualReturn} more per year (assuming a 5% return).",
        report_local_no_data: "Insufficient data for a detailed analysis. Please input your income and expenses.",
        section_debt_title: "Debt Management",
        tooltip_debt: "Manage your debts. We'll help you calculate a 'Debt Avalanche' plan, prioritizing high-interest debts.",
        label_debt_name: "Debt Name",
        label_debt_balance: "Current Balance",
        label_debt_rate: "Interest Rate (%)",
        label_debt_min_payment: "Min. Monthly Payment",
        btn_add_debt: "Add Debt",
        label_debt_extra_payment: "Extra Monthly Payment",
        section_goals_title: "Financial Goal Setting",
        tooltip_goals: "Add and manage your financial goals. Update your progress by adding to your saved amount.",
        label_goal_name: "Goal Name",
        label_goal_target: "Target Amount",
        btn_add_goal: "Add Goal",
        section_trends_title: "Financial Trend Analysis",
        tooltip_trends: "Record your data at the end of each month to track your financial changes over time.",
        btn_record_history: "Record This Month's Data",
        placeholder_goal: 'e.g., Trip to Europe',
        placeholder_debt: 'e.g., Credit Card A',
        section_category_title: "Category Management",
        tooltip_category: "Add, view, and delete your expense categories here.",
        label_category_name: "Category Name",
        label_category_type: "Category Type",
        btn_add_category: "Add Category",
        label_expense_name: "Other Expense",
        label_expense_amount: "Amount",
        btn_add_expense: "Add Other Expense",
        label_api_key: 'Gemini API Key',
        placeholder_api_key: 'Paste your API key here',
        section_what_if_title: "What-If Scenario Analysis",
        tooltip_what_if: "Simulate how hypothetical income/expense changes affect your debt payoff timeline.",
        label_scenario_income: "Monthly Net Income Change (%)",
        label_scenario_expense: "Monthly Fixed Expense Change",
        btn_run_scenario: "Run Scenario"
    },
    ko: {
        app_title: '스마트 예산 노트',
        section_calculation_mode_title: '계산 방식',
        mode_simple: '기본',
        mode_advanced: '고급',
        tooltip_calculation_mode: "계산 방식을 선택합니다. '기본 모드'는 세후 순수입을 기준으로, '고급 모드'는 세전 총수입과 각종 공제 항목을 직접 입력하여 더 상세하게 계산합니다.",
        section_net_income_title: '순수입',
        label_net_income: '월 순수입 (세후)',
        tooltip_net_income: "세금과 공제 항목이 모두 빠져나간 후, 실제로 통장에 입금되는 월 순수입을 입력합니다.",
        section_salary_title: '총수입',
        tooltip_salary: "세금을 제하기 전의 총 수입을 입력합니다. '추가 수입' 버튼으로 비정기적인 수입을 더할 수 있습니다.",
        label_base_salary: '기본 급여',
        frequency_monthly: '월별',
        frequency_annually: '연간',
        frequency_weekly: '주별',
        frequency_bi_weekly: '2주별',
        btn_add_income: '추가 수입',
        label_annual_salary: '연간 총수입:',
        section_taxes_title: '세금',
        tooltip_taxes: "급여에서 원천징수되는 세금 항목들을 입력합니다.",
        label_frequency: '주기',
        label_federal_withholding: '연방세',
        label_state_tax: '주세',
        label_oasdi: '사회보장세 (OASDI)',
        label_medicare: '메디케어',
        label_ca_sdi: 'CA 장애보험 (CASDI)',
        btn_add_item: '항목 추가',
        section_pre_tax_title: '세전 공제',
        tooltip_pre_tax: "세금을 부과하기 전에 총수입에서 공제되는 항목들입니다. 주로 401k와 같은 연금 저축이나 특정 보험료가 해당됩니다.",
        label_medical_premium: '의료 보험료',
        label_dental_premium: '치과 보험료',
        label_vision_premium: '안과 보험료',
        label_401k_traditional: '401k (Traditional)',
        section_post_tax_title: '세후 공제',
        tooltip_post_tax: "세금을 납부한 후, 순수입에서 공제되는 항목들입니다.",
        label_spp: '자사주 매입 계획 (SPP)',
        label_adnd: '사고사망 및 상해보험 (AD&D)',
        label_401k_roth: '401k (Roth)',
        label_ltd: '장기 장애 보험 (LTD)',
        label_critical_illness: '중대질병 보험',
        label_accident_insurance: '상해 보험',
        label_legal_services: '법률 서비스',
        section_expenses_title: '지출 관리',
        tooltip_expenses: "순수입(실수령액)에서 나가는 모든 지출을 입력합니다.",
        label_rent_mortgage: '월세/주택담보대출',
        label_utilities: '공과금',
        label_internet: '인터넷',
        label_phone: '통신비',
        label_groceries: '식료품',
        label_dining_out: '외식',
        label_transportation: '교통',
        label_shopping: '쇼핑',
        label_health_wellness: '건강/웰빙',
        label_entertainment: '오락/여가',
        label_insurance: '보험',
        label_donation: '기부',
        label_travel: '여행',
        label_pets: '반려동물',
        label_children: '자녀 양육비',
        section_summary_title: '예산 요약',
        tooltip_summary: "모든 수입과 지출을 종합한 최종 요약입니다.",
        label_summary_frequency: '요약 주기',
        label_gross_salary: '총수입:',
        label_total_taxes: '총 세금:',
        label_total_pre_tax: '총 세전 공제:',
        label_total_post_tax: '총 세후 공제:',
        label_net_salary: '순수입 (실수령액):',
        label_total_expenses: '총 지출:',
        label_remaining_budget: '남은 예산:',
        label_savings_rate: '저축률',
        section_budget_rule_title: '예산 규칙 적용',
        tooltip_budget_rule: "널리 알려진 예산 규칙을 선택하여 현재 지출이 순수입(실수령액) 기준 목표에 얼마나 부합하는지 시각적으로 확인합니다.",
        rule_50_30_20_title: '50/30/20 규칙 (필수/선택/저축)',
        rule_70_20_10_title: '70/20/10 규칙 (지출/저축/부채)',
        rule_80_20_title: '80/20 규칙 (지출/저축)',
        section_ai_title: 'AI 지출 보고서',
        tooltip_ai_report: "입력된 데이터를 바탕으로 현재 재무 상태를 분석하고 개선을 위한 조언을 제공합니다.",
        ai_report_placeholder: '"AI 보고서 생성"을 클릭하여 분석 결과를 확인하세요.',
        section_data_title: '데이터 관리',
        tooltip_data_management: "현재까지 입력한 모든 데이터를 파일로 저장(Export)하거나, 저장했던 파일을 불러올(Import) 수 있습니다.",
        btn_export: '내보내기',
        btn_import: '가져오기',
        btn_clear_all_data: '전체 삭제',
        btn_print: '인쇄',
        btn_email: '이메일',
        btn_share: '공유',
        custom_item_name: '항목 이름',
        custom_income_name: '수입 이름',
        custom_item_amount: '금액',
        custom_item_category: '카테고리',
        remove: '삭제',
        confirm_clear_data: '정말 모든 데이터를 지우시겠습니까?',
        confirm_import_data: '기존 데이터를 덮어씁니다. 계속하시겠습니까?',
        invalid_json: '유효하지 않은 JSON 파일입니다.',
        alert_data_loaded: "데이터를 성공적으로 가져왔습니다!",
        tag_needs: '필수',
        tag_wants: '선택',
        tag_savings: '저축',
        tag_debt: '부채',
        tag_fixed: '고정',
        rule_category_needs: '필수 지출',
        rule_category_wants: '선택 지출',
        rule_category_savings: '저축',
        rule_category_savings_debt: '저축 & 부채',
        rule_category_spending: '지출 (필수+선택)',
        rule_category_debt: '부채 상환',
        rule_category_surplus: '잉여금',
        modal_title_needs: '필수 지출 항목',
        modal_title_wants: '선택 지출 항목',
        modal_title_savings: '저축 항목',
        modal_title_savings_debt: '저축 & 부채 항목',
        modal_title_spending: '지출 항목',
        modal_title_debt: '부채 상환 항목',
        report_local_generating: "로컬 분석 리포트를 생성 중입니다...",
        report_local_failed: "로컬 리포트 생성에 실패했습니다. 데이터를 확인해주세요.",
        report_local_title: "재무 건강 분석 리포트",
        report_local_summary_title: "1. 재무 현황 요약",
        report_local_summary_text: "{summaryFreq} 순수입 {netIncome}을 기준으로, 저축률은 <strong>{savingsRate}%</strong>이며, <strong>{remaining}</strong>의 추가 잉여금이 있습니다. 재정 운용의 강점은 <strong>{strength}</strong>이며, <strong>{weakness}</strong> 부분에서 개선의 여지가 있습니다.",
        report_local_strength: "계획적인 저축",
        report_local_weakness: "높은 선택 지출 비중",
        report_local_no_weakness: "균형 잡힌 관리",
        report_local_recommendation_title: "2. 추천 실행 계획",
        report_local_tip_overspending: "'{category}' 항목 지출({amount})이 예산 규칙을 초과했습니다. 이 부분을 10~15% 줄이는 것을 고려해보세요.",
        report_local_tip_high_wants: "선택적 지출('선택')이 소득의 {wantsPercentage}%를 차지합니다. 이 항목들을 검토하면 저축액을 크게 늘릴 수 있습니다.",
        report_local_tip_low_savings: "현재 저축률은 {savingsRate}%입니다. 재무 목표를 빠르게 달성하기 위해, 잉여금을 저축에 배분하거나 불필요한 지출을 줄여 저축률을 높여보세요.",
        report_local_tip_surplus: "<strong>{remaining}</strong>의 잉여금이 있습니다! 이 금액을 저축이나 투자에 활용하면, 연 5% 수익률 가정 시 연간 약 <strong>{annualReturn}</strong>의 추가 수익을 기대할 수 있습니다.",
        report_local_no_data: "상세 분석을 위한 데이터가 부족합니다. 수입 및 지출 내역을 입력해주세요.",
        section_debt_title: "부채 관리",
        tooltip_debt: "상환할 부채 목록을 관리합니다. 이자율이 높은 순서대로 상환하는 '눈사태(Avalanche)' 전략을 계산해 드립니다.",
        label_debt_name: "부채 이름",
        label_debt_balance: "현재 잔액",
        label_debt_rate: "이자율 (%)",
        label_debt_min_payment: "월 최소상환액",
        btn_add_debt: "부채 추가",
        label_debt_extra_payment: "월 추가 상환액",
        section_goals_title: "재무 목표 설정",
        tooltip_goals: "달성하고 싶은 재무 목표를 추가하고 관리합니다. '저축액 추가'에 금액을 입력하여 달성률을 업데이트할 수 있습니다.",
        label_goal_name: "목표 이름",
        label_goal_target: "목표 금액",
        btn_add_goal: "목표 추가",
        section_trends_title: "재무 트렌드 분석",
        tooltip_trends: "매월 말 '이번 달 데이터 기록하기' 버튼을 눌러 데이터를 저장하고, 시간 경과에 따른 재무 변화를 차트로 확인하세요.",
        btn_record_history: "이번 달 데이터 기록하기",
        placeholder_goal: '예: 유럽 여행',
        placeholder_debt: '예: 신용카드 A',
        section_category_title: "카테고리 관리",
        tooltip_category: "지출 카테고리를 직접 추가, 확인, 삭제할 수 있습니다.",
        label_category_name: "카테고리 이름",
        label_category_type: "카테고리 종류",
        btn_add_category: "카테고리 추가",
        label_expense_name: "기타 지출 항목",
        label_expense_amount: "금액",
        btn_add_expense: "기타 지출 추가",
        label_api_key: 'Gemini API 키',
        placeholder_api_key: '이곳에 API 키를 붙여넣으세요',
        section_what_if_title: "What-If 시나리오 분석",
        tooltip_what_if: "가상의 수입/지출 변화가 부채 상환 완료 시점에 미치는 영향을 시뮬레이션합니다.",
        label_scenario_income: "월 순수입 변화 (%)",
        label_scenario_expense: "월 고정지출 변화",
        btn_run_scenario: "시나리오 실행"
    }
};

// ... (The rest of the JS code follows) ...
