- name: Deploy files
  uses: appleboy/scp-action@v0.1.4
  with:
    host: ${{ secrets.SSH_HOST }}  # 오라클 인스턴스 공인 IP
    username: ubuntu               # 오라클 기본 사용자 (ubuntu)
    key: ${{ secrets.SSH_PRIVATE_KEY }}
    port: 22                       # 명시적 포트 지정
    source: "./"
    target: "/var/www/html"
