# deploy.yml 대체 코드 (SFTP 버전)
- name: Deploy via SFTP
  uses: appleboy/scp-action@master
  with:
    host: ${{ secrets.SSH_HOST }}  # 서버 IP/도메인
    username: ${{ secrets.SSH_USERNAME }}  # SSH 사용자 (일반적으로 ubuntu)
    key: ${{ secrets.SSH_KEY }}  # 서버 SSH 키 (cat ~/.ssh/id_rsa.pub)
    source: "./"
    target: "/var/www/html"
