name: Deploy to Server

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: "144.24.67.238"
          username: "ubuntu"
          key: "${{secrets.SSH_PRIVATE_KEY}}"
          port: "22"
          script: |
            cd /var/www/html
            git reset --hard
            git pull origin main
            sudo systemctl restart nginx
